name: Windows Release
on:
  push:
    tags:
      - v*
jobs:
  change-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: ".github/release-notes.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - shell: bash
        run: |
          printf %s "${{steps.github_release.outputs.changelog}}" > change-log.txt
      - name: Upload change log
        uses: actions/upload-artifact@v2
        with:
          name: change-log
          path: change-log.txt

  release-windows-dist:
    runs-on: ubuntu-latest
    needs: [change-log]
    steps:
      - name: Download change-log
        uses: actions/download-artifact@v2
        with:
          name: change-log
      - name: Set the value
        id: step_one
        run: |
          echo 'CHANGELOG<<EOF' >> $GITHUB_ENV
          cat change-log.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      # Release!
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "Awscert Build ${{ github.ref }}:\n${{env.CHANGELOG}}"
          draft: false
          prerelease: true
