name: "changelog"
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: print changelog
        run: |
          echo ${{steps.build_changelog.outputs.changelog}}
